### ISSUE TITLE
No Module named 'Crypto'

### ISSUE THREAD

**Issue by graxe20** [TaxMachine/Grabbers-Deobfuscator#14]
```
Traceback (most recent call last):
  File "D:\Downloads\Grabbers-Deobfuscator-main\Grabbers-Deobfuscator-main\deobf.py", line 17, in <module>
    from utils.pyinstaller.pyinstaller import ExtractPYInstaller
  File "D:\Downloads\Grabbers-Deobfuscator-main\Grabbers-Deobfuscator-main\utils\pyinstaller\pyinstaller.py", line 2, in <module>
    from utils.pyinstaller.extractors.pyinstxtractorng import PyInstArchive as PyInstArchiveNG
  File "D:\Downloads\Grabbers-Deobfuscator-main\Grabbers-Deobfuscator-main\utils\pyinstaller\extractors\pyinstxtractorng.py", line 25, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
```

**Comment by TaxMachine** [comment]
Did you install pycryptodome ob the right py version?

**Comment by graxe20** [comment]
I think so, what's the correct version?

**Comment by TaxMachine** [comment]
Depends which one you're using, for example if you're using python2 as default `python` environment then you have to install it with the right pip version. If it's python3 you prbly have to do `python3 -m pip install -r requirements.txt`

**Comment by graxe20** [comment]
Will try that shortly and let you know. Thanks.

**Comment by graxe20** [comment]
Still get the same error back,

```py
Traceback (most recent call last):
  File "D:\Downloads\Grabbers-Deobfuscator-main\Grabbers-Deobfuscator-main\deobf.py", line 17, in <module>
    from utils.pyinstaller.pyinstaller import ExtractPYInstaller
  File "D:\Downloads\Grabbers-Deobfuscator-main\Grabbers-Deobfuscator-main\utils\pyinstaller\pyinstaller.py", line 2, in <module>
    from utils.pyinstaller.extractors.pyinstxtractorng import PyInstArchive as PyInstArchiveNG
  File "D:\Downloads\Grabbers-Deobfuscator-main\Grabbers-Deobfuscator-main\utils\pyinstaller\extractors\pyinstxtractorng.py", line 25, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
```

**Comment by TaxMachine** [comment]
Weird idk why it does that

**Comment by waxnet** [comment]
> Still get the same error back,
> 
> ```python
> Traceback (most recent call last):
>   File "D:\Downloads\Grabbers-Deobfuscator-main\Grabbers-Deobfuscator-main\deobf.py", line 17, in <module>
>     from utils.pyinstaller.pyinstaller import ExtractPYInstaller
>   File "D:\Downloads\Grabbers-Deobfuscator-main\Grabbers-Deobfuscator-main\utils\pyinstaller\pyinstaller.py", line 2, in <module>
>     from utils.pyinstaller.extractors.pyinstxtractorng import PyInstArchive as PyInstArchiveNG
>   File "D:\Downloads\Grabbers-Deobfuscator-main\Grabbers-Deobfuscator-main\utils\pyinstaller\extractors\pyinstxtractorng.py", line 25, in <module>
>     from Crypto.Cipher import AES
> ModuleNotFoundError: No module named 'Crypto'
> ```

do you have more than one python version installed?

**Comment by TaxMachine** [comment]
That's weird

**Comment by waxnet** [comment]
might be bc he has more than 1 version of python installed so the modules get installed on another version and not on the right one

**Comment by TaxMachine** [comment]
Is it still not working or can I close this issue?

**Comment by graxe20** [comment]
I might have 2 versions but I think I uninstalled all versions and just installed the version suggested.

I'll give it a try, feel free to close the issue and I can open another one when I've tried again as it might be a while :)
